version: "3.4"

services:

  kibana:
    image: docker.elastic.co/kibana/kibana@sha256:0d2565286641d213fdbc26ffe29c33268d31e4820ea7af636ebc7d879d736895
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.4.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - network.bind_host=0.0.0.0
      - xpack.security.enabled=false
    command: "elasticsearch -E cluster.name=local -E discovery.type=single-node"
 
  elastichq:
    image: elastichq/elasticsearch-hq
    ports:
      - 5000:5000
    environment:
      HQ_DEFAULT_URL: http://elasticsearch:9200 
