#! /usr/bin/env bash

docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
docker pull cshr/lpg-learning-catalogue || true
./gradlew init
./gradlew build
docker build -t cshr/lpg-learning-catalogue:latest .
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
docker tag cshr/lpg-learning-catalogue:latest cshr/lpg-learning-catalogue:${TRAVIS_COMMIT}
docker push cshr/lpg-learning-catalogue

export PATH="`pwd`/pyhome/bin:${PATH}"
export PYTHONPATH="`pwd`/pyhome/lib/python/site-packages:${PYTHONPATH}"
export PYTHONPATH="`pwd`/pyhome/lib/python2.7/site-packages:${PYTHONPATH}"
python -c "import ansible, sys; sys.exit(0) if ansible.__version__ == '2.4.3.0' else sys.exit(1)"
if [ $? -ne 0 ]; then
  rm -rf pyhome
  PYTHONUSERBASE=pyhome pip install --user ansible==2.4.3.0
fi

#./environ/deploy dev ${TRAVIS_COMMIT}
