#!/bin/bash

set -e -o pipefail

counter=0

function stage {
  ((counter++)) || true
  printf "\n\033[34;1m➡  $1  \033[90m[stage $counter] [running ${SECONDS}s]\033[0m\n\n"
}

stage "Running a gradle build"
./gradlew build

stage "Building the new lpg-learning-catalogue docker image"
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
docker pull cshr/lpg-learning-catalogue || true
docker build -t cshr/lpg-learning-catalogue:latest .
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

stage "Pushing the learning-catalogue ${TRAVIS_COMMIT} docker image"
docker tag cshr/lpg-learning-catalogue:latest cshr/lpg-learning-catalogue:${TRAVIS_COMMIT}
docker push cshr/lpg-learning-catalogue

#./environ/deploy dev ${TRAVIS_COMMIT}

echo "Total run time: ${SECONDS}s"